#!/usr/bin/env python3
"""
encode.py
   RV32 instruction encoder for the *custom* opcode set used by the
   accompanying CPU. Produces a hex file readable by $readmemh.

   Custom opcodes (decimal):
       R-type       = 34   add/and/or/xor/sltu/srl/sra
       I-type ALU+LW= 14   addi/andi/ori/lw
       JALR         = 68
       BRANCH       = 64   bne/bge
       JAL          = 70
       SW           = 24
"""

OP_R, OP_I, OP_JALR, OP_BR, OP_JAL, OP_SW = 34, 14, 68, 64, 70, 24

def r(f7, rs2, rs1, f3, rd):
    return (f7 << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | OP_R

def i(imm, rs1, f3, rd, op=OP_I):
    imm12 = imm & 0xFFF
    return (imm12 << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | op

def s(imm, rs2, rs1, f3):
    imm12 = imm & 0xFFF
    hi = (imm12 >> 5) & 0x7F
    lo = imm12 & 0x1F
    return (hi << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (lo << 7) | OP_SW

def b(imm, rs2, rs1, f3):
    imm13 = imm & 0x1FFF
    b12   = (imm13 >> 12) & 1
    b10_5 = (imm13 >>  5) & 0x3F
    b4_1  = (imm13 >>  1) & 0xF
    b11   = (imm13 >> 11) & 1
    return (b12 << 31) | (b10_5 << 25) | (rs2 << 20) | (rs1 << 15) | \
           (f3 << 12) | (b4_1 << 8) | (b11 << 7) | OP_BR

def j(imm, rd):
    imm21    = imm & 0x1FFFFF
    b20      = (imm21 >> 20) & 1
    b10_1    = (imm21 >>  1) & 0x3FF
    b11      = (imm21 >> 11) & 1
    b19_12   = (imm21 >> 12) & 0xFF
    return (b20 << 31) | (b10_1 << 21) | (b11 << 20) | (b19_12 << 12) | \
           (rd << 7) | OP_JAL

# Mnemonics
def addi(rd, rs1, imm): return i(imm, rs1, 1, rd)
def andi(rd, rs1, imm): return i(imm, rs1, 0, rd)
def ori (rd, rs1, imm): return i(imm, rs1, 7, rd)
def lw  (rd, rs1, imm): return i(imm, rs1, 3, rd)
def jalr(rd, rs1, imm): return i(imm, rs1, 1, rd, op=OP_JALR)
def add (rd, rs1, rs2): return r(10, rs2, rs1, 1, rd)
def _and(rd, rs1, rs2): return r(10, rs2, rs1, 0, rd)
def _or (rd, rs1, rs2): return r(10, rs2, rs1, 7, rd)
def xor (rd, rs1, rs2): return r(10, rs2, rs1, 5, rd)
def sltu(rd, rs1, rs2): return r( 1, rs2, rs1, 4, rd)
def srl (rd, rs1, rs2): return r(10, rs2, rs1, 6, rd)
def sra (rd, rs1, rs2): return r(30, rs2, rs1, 6, rd)
def sw  (rs2, rs1, imm): return s(imm, rs2, rs1, 3)
def bne (rs1, rs2, imm): return b(imm, rs2, rs1, 2)
def bge (rs1, rs2, imm): return b(imm, rs2, rs1, 6)
def jal (rd, imm):       return j(imm, rd)
def nop(): return addi(0, 0, 0)

# -------------------------------------------------------------------------
# Demo program: arithmetic, load/store round-trip, taken & not-taken branch
#
#   Expected final state:
#     x1=5  x2=7   x3=12   x4=4   x5=7  x6=11
#     x7=100  x8=12   x9=99  x10=17  x11=42
# -------------------------------------------------------------------------
prog = [
    ("addi  x1,  x0,  5",          addi(1,  0, 5)),
    ("addi  x2,  x0,  7",          addi(2,  0, 7)),
    ("add   x3,  x1,  x2",         add (3,  1, 2)),     # x3=12
    ("and   x4,  x3,  x1",         _and(4,  3, 1)),     # x4=4
    ("or    x5,  x4,  x2",         _or (5,  4, 2)),     # x5=7
    ("xor   x6,  x3,  x2",         xor (6,  3, 2)),     # x6=11
    ("addi  x7,  x0,  100",        addi(7,  0, 100)),
    ("sw    x3,  0(x7)",           sw  (3,  7, 0)),     # mem[25]=12
    ("nop",                        nop()),              # bubble before lw
    ("lw    x8,  0(x7)",           lw  (8,  7, 0)),     # x8=12
    ("add   x10, x8,  x1",         add (10, 8, 1)),     # load-use: stall+forward, x10=17
    # not-taken branch test
    ("bne   x1,  x1,  +8",         bne (1,  1, 8)),     # not taken (x1==x1)
    ("addi  x9,  x0,  99",         addi(9,  0, 99)),    # executed -> x9=99
    # taken branch test
    ("bne   x1,  x2,  +8",         bne (1,  2, 8)),     # taken (5 != 7)
    ("addi  x11, x0,  77",         addi(11, 0, 77)),    # SKIPPED
    ("addi  x11, x0,  42",         addi(11, 0, 42)),    # x11=42
    # halt loop
    ("nop",                        nop()),
    ("nop",                        nop()),
]

if __name__ == "__main__":
    print("// Auto-generated by encode.py   (one 32-bit word per line)")
    for i_addr, (mnem, word) in enumerate(prog):
        print(f"{word:08x}    // 0x{4*i_addr:04x}:  {mnem}")
